/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */

// @ts-check

/** @type { import('@docusaurus/plugin-content-docs').SidebarsConfig } */
const sidebars = {
  tutorialSidebar: [{"type": "autogenerated", "dirName": "."}],
    tutorialSidebar: [
    [{'type': 'category', 'label': 'device-management', 'items': ['device-management/device-management']}, {'type': 'category', 'label': 'rdk-camera-architecture', 'items': ['rdk-camera-architecture/rdk-camera-architecture']}, {'type': 'category', 'label': 'rdk-camera-documentation', 'items': ['rdk-camera-documentation/rdk-camera-documentation']}]
  ],
};

export default sidebars;
